name:                HaskellDevEnv
version:             0.1.0.0
github:              "IamMaxim/HaskellDevEnv"
license:             BSD3
author:              "Maxim Stepanov"
maintainer:          "g.maxim.stepanoff@gmail.com"
copyright:           "2021 IamMaxim"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/IamMaxim/HaskellDevEnv#readme>

dependencies:
- base >= 4.7 && < 5
- codeworld-api == 0.7.0
- text == 1.2.4.0

library:
  source-dirs: src

executables:
  HaskellDevEnv-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellDevEnv

tests:
  HaskellDevEnv-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellDevEnv
